### PR TITLE
[BUGFIX] Only request provider default scopes if available

### PR DESCRIPTION
**Pull request by liayn**
Resolves: #148

### CODE REVIEW

**Comment by liayn** [comment]
This is my untested draft. What do you think @wazum?

**Comment by liayn** [comment]
@wazum Did you actually test it already?

**Comment by wazum** [comment]
@liayn yes, I use the patch from here for the client project

**Comment by liayn** [comment]
I needed this fix myself now too.

@xperseguers  Please merge and release. Thanks.

**Pull request merged**
