### PR TITLE
[FEATURE] Merge with existing fe_user if username matches email

### PR DESCRIPTION
**Pull request by liayn**

### CODE REVIEW

**Comment by xperseguers** [comment]
What's the purpose of keeping the current password? Doesn't it sound better to reset it every time as it's useless anyway?

**Comment by liayn** [comment]
It's no useless at all. A user can always choose to login with user/pwd or via openid connect.

**Comment by xperseguers** [comment]
Well, in all the scenarios I've worked with the purpose of using OpenID was to have it as SSO, as such password should not be managed by TYPO3.

**Comment by liayn** [comment]
Example: SkillDisplay.
You may have an existing user already and later choose to use your TYPO3 account to login.
Then of course the accounts should be merged, aka the existing account should be used and TYPO3 SSO is only one possible way to login.

**Comment by liayn** [comment]
Thanks!

**Pull request merged**
