### PR TITLE
[FEATURE] Add a custom user groups event

### PR DESCRIPTION
**Pull request by denislorch**
* to map the groups by a a different pattern if "Roles" does not fit
* for example work with "claims" or "group_membership" data in a custom listener

Re-Implement https://github.com/xperseguers/t3ext-oidc/pull/86 under v2.0.0 (TYPO3 v11)

### CODE REVIEW

**Comment by liayn** [comment]
Please add proper typehints wherever possible

**Comment by denislorch** [comment]
Added them (support for PHP v7.4 still needed).

**Comment by liayn** [comment]
If https://github.com/xperseguers/t3ext-oidc/pull/152 is accepted, I'd suggest adding the reference to the auth service for this new event as well.

**Comment by liayn** [comment]
@denislorch #152 is merged please add the reference as well here, so we can proceed with this one.

**Comment by denislorch** [comment]
Streamlined to latest changes, to be a part of the next release.

**Comment by liayn** [comment]
Looks good to me. Thanks.

**Review by liayn — APPROVED** [review]

**Review by xperseguers — APPROVED** [review]

**Pull request merged**
