### PR TITLE
[BUGFIX] #70 Fix login with oidc key mappings in TYPO3 10

### PR DESCRIPTION
**Pull request by SomeBdyElse**
Fix an exception that occurred in TYPO3 10 during the login process,
if a TypoScript mapping was present. The bug occurred in an incorrect
initialization of a fake TSFE within the Authentication Service. Fix
the initialization with code compatible to TYPO3 10.

### CODE REVIEW

**Comment by SomeBdyElse** [comment]
Hi @xperseguers ! I fixed #70 for TYPO3 10. However, I am not sure whether the code is still TYPO3 9 compatible. Please have a look whether you like the general approach.

**Comment by xperseguers** [comment]
The approach looks good, even for v9, but I don't have any v9 instance anymore for actual real testing :/

**Comment by DanielSiepmann** [comment]
Is there anything I could do to support you in fixing the issue?

**Comment by liayn** [comment]
This this still relevant?

**Comment by liayn** [comment]
v10 is outdated meanwhile and we do not support this version with new fixes.
Closing this one therefore. Still, thanks for your contribution.

**Pull request closed without merging**
